#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Secret", "metadata":{"name":"cartographer-conventions-ca-certificates"}})
---
data:
  ca-certificates.crt: #@ data.values.ca_cert_data
