#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata":{"name":"cartographer-controller"}})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by="name"
      - name: cartographer-controller
        #@overlay/match missing_ok=True
        args:
          #@overlay/append
          - #@ "-max-concurrent-deliveries=" + str(data.values.cartographer.concurrency.max_deliveries)
          - #@ "-max-concurrent-workloads=" + str(data.values.cartographer.concurrency.max_workloads)
          - #@ "-max-concurrent-runnables=" + str(data.values.cartographer.concurrency.max_runnables)
        #@overlay/match missing_ok=True
        resources: #@ data.values.cartographer.resources
