
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cartographer-aggregate-app-view
  labels:
    platform.kadras.io/aggregate-to-app-view: "true"
rules:
  - apiGroups:
      - carto.run
    resources:
      - deliverables
      - runnables
      - workloads
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - conventions.carto.run
    resources:
      - podintents
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cartographer-aggregate-app-edit
  labels:
    platform.kadras.io/aggregate-to-app-edit: "true"
rules:
  - apiGroups:
      - carto.run
    resources:
      - deliverables
      - workloads
    verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cartographer-aggregate-app-view-cluster-access
  labels:
    platform.kadras.io/aggregate-to-app-view-cluster-access: "true"
rules:
  - apiGroups:
      - carto.run
    resources:
      - clusterconfigtemplates
      - clusterdeliveries
      - clusterdeploymenttemplates
      - clusterimagetemplates
      - clusterruntemplates
      - clustersourcetemplates
      - clustersupplychains
      - clustertemplates
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - conventions.carto.run
    resources:
      - clusterpodconventions
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cartographer-aggregate-app-operate-cluster-access
  labels:
    platform.kadras.io/aggregate-to-app-operate-cluster-access: "true"
rules:
  - apiGroups:
      - carto.run
    resources:
      - clusterconfigtemplates
      - clusterdeliveries
      - clusterdeploymenttemplates
      - clusterimagetemplates
      - clusterruntemplates
      - clustersourcetemplates
      - clustersupplychains
      - clustertemplates
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - conventions.carto.run
    resources:
      - clusterpodconventions
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
